apiVersion: v1
kind: Namespace
metadata:
  name: neuvector
  labels:
    name: neuvector
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: neuvector
  namespace: neuvector
spec:
  url: https://github.com/neuvector/neuvector-helm/charts/
  interval: 1m
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: core
  namespace: neuvector
spec:
  interval: 5m
  chart:
    spec:
      chart: core
      version: "1.9.1"
      sourceRef:
        kind: HelmRepository
        name: neuvector
        namespace: neuvector
      interval: 1m