apiVersion: v1
kind: Service
metadata:
  name: minecraft
  namespace: minecraft
  labels:
    app: minecraft-minecraft
spec:
  ports:
  - port: 8080
    targetPort: 25565
  selector:
    app: minecraft-minecraft
  type: NodePort