apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minecraft
  namespace: minecraft
spec:
  releaseName: minecraft
  chart:
    spec:
      chart: minecraft
      sourceRef:
        kind: HelmRepository
        name: minecraft
        namespace: flux-system
  interval: 5m
  install:
    remediation:
      retries: 3
  values:
    minecraftServer:
      eula: "TRUE"
      difficulty: normal
      ops: astroe
    persistence:
      dataDir:
        enabled: true
