apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
  labels:
    name: istio-system
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: istio-base
  namespace: istio-system
spec:
  url: https://istio-release.storage.googleapis.com/charts
  interval: 1m
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-base
  namespace: istio-system
spec:
  interval: 5m
  chart:
    spec:
      chart: base
      version: "1.13.2"
      sourceRef:
        kind: HelmRepository
        name: istio-base
        namespace: istio-system
      interval: 1m