apiVersion: v1
kind: Namespace
metadata:
  name: istio-ingress
  labels:
    name: istio-ingress
    istio-injection: enabled
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: istio-gateway
  namespace: istio-ingress
spec:
  url: https://istio-release.storage.googleapis.com/charts
  interval: 1m
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-gateway
  namespace: istio-ingress
spec:
  interval: 5m
  chart:
    spec:
      chart: gateway
      version: "1.13.2"
      sourceRef:
        kind: HelmRepository
        name: istio-gateway
        namespace: istio-ingress
      interval: 1m