apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-base
  namespace: istio-system
spec:
  releaseName: istio-base
  chart:
    spec:
      chart: istio/base
      version: "1.16.0"
      sourceRef:
        kind: HelmRepository
        name: istio-base
        namespace: istio-system
  interval: 5m
