apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-gateway
  namespace: istio-system
spec:
  interval: 5m
  chart:
    spec:
      chart: gateway
      version: "1.13.2"
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
      interval: 1m